image: moul/emacs

pages:
   stage: deploy
   script:
     - emacs --batch --eval "(progn (package-initialize) (add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t) (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t) (package-refresh-contents) (package-install 'org) (package-install 'org-plus-contrib) (package-install 'htmlize)"
     - emacs evaluacion-2020-1.org --batch --eval "(require 'ox)" --eval "(org-html-export-to-html)"
     - mkdir .public
     - cp -r assets im styles .public
     - cp main.html .public/manual.html
     - cp evaluacion-2020-1.html .public/index.html
     - cp papers*.html .public
     - cp sitemap.xml .public
     - mv .public public 
   artifacts:
     paths:
     - public
   only:
   - master 
