* Evaluación para el semestre 2018-2

** Guía del curso

El curso tiene una guía de elementos mínimos  que debes conocer para aprobar la asignatura. Eres
el único  que tiene la  obligación de revisar  cuales son dichos  elementos y asegurarte  que el
profesor los explique durante la clase.

La guía esta disponible en  formato [[assets/manual.pdf][PDF]] y [[manual.html][HTML]]. Es recomendable que tengas  una copia de la guía
durante la clase.

** Elementos del curso

*** Horarios de clase

Los horarios de clase son:

1. Lunes y jueves 10:00 a 13:00 (solo alumnos de nuevo ingreso)
2. Lunes y miércoles 17:00 a 19:00
3. Lunes y miércoles 19:00 a 21:00

Al primer horario solo pueden asistir alumnos de nuevo ingreso.

Si no eres alumno de nuevo ingreso y tomando en cuenta que las clases podrían no ser las mismas,
tienes el derecho a  asistir en cualquiera de los horarios vespertinos.   Toma en cuenta también
que si tomas la clase en un grupo que no te corresponde podría afectar tus participaciones.

En  cualquier caso:  **Memoriza  tu  número de  grupo**.  El grupo  al  que  perteneces te  será
solicitado en los exámenes  y no será permitido preguntarlo ni levantarse a  ver los horarios en
la puerta del salón.

*** Participaciones

Durante el semestre se  no tomará en cuenta asistencia ni puntualidad.  Puedes asistir, llegar y
marcharte a la hora que quieras. Sin embargo el curso es presencial, debido a esto se tomarán en
cuenta las participaciones en clase.

Necesitarás  dieciséis participaciones  para  tener  derecho a  una  calificación  al final  del
semestre, puedes conseguirlas mediante estas opciones:

- Aportaciones en clase.
- Revisiones de tus trabajos.
- Entregar actividades que fortalezcan tu aprendizaje.

*** Evaluación en periodo ordinario

Tienes dos opciones para aprobar la materia de forma ordinaria:

1. Trabajo escrito. Escogerás un tema relacionado con las materias que haz aprobado o que cursas
   durante el semestre  2018-2.  Tu expediente, tira  de materias y temario  de asignatura serán
   las pruebas de  que haz seleccionado correctamente  el tema.  Escribirás un  trabajo de dicho
   tema. El  trabajo deberá  aprobar la rúbrica  R1 y  será calificado con  la rúbrica  R2.  Los
   avances de tu trabajo podrán ser revisados las  veces que quieras, si entre revisiones no hay
   mejoras considerables este derecho podrá suspenderse.
2. Trabajo de exposición. Escogerás un tema relacionado  con las materias que haz aprobado o que
   cursas durante el semestre  2018-2.  Tu expediente, tira de materias  y temario de asignatura
   serán las pruebas de que haz seleccionado correctamente el tema. Realizarás al menos un video
   en el  que expliques  el tema con  claridad.  El video  deberá aprobar  la rúbrica R3  y será
   calificado con la rúbrica R4.

Es posible  entregar ambos trabajos  siempre y  cuando sean del  mismo tema. Todos  los trabajos
deben  ser entregados  en papel  para su  revisión a  lo largo  del semestre.  La entrega  final
constará de un folder con los siguientes elementos y en este orden:

- Una hoja con tu nombre, grupo y las rúbricas adecuadas para calificar el trabajo.
- Las revisiones a las que fue sometido el trabajo a lo largo del semestre.
- Una copia engrapada del trabajo final (solo trabajo escrito).
- Una copia digital del trabajo en un CD o DVD correctamente rótulado con tu nombre y tu grupo.

**Importante**: No serán admisibles estos documentos si tienen textos escritos a mano.

Se pueden entregar dos  trabajos en el mismo folder, en ese caso  será necesario colocar primero
los documentos del trabajo escrito y después los documentos del trabajo de exposición.

**** Calificación

La calificación del curso se obtendrá de la siguiente manera:

1. Si no se entrega ningún trabajo: NP.
2. Si se entrega un trabajo se calificará ese trabajo en escala de cero a diez.
3. Si  se entregan dos trabajos  se calificarán ambos  trabajos en escala  de cero a diez.  A la
   calificación más alta se le sumará la mitad de la calificación más baja.

*** Actividades optativas

1. Leerás  el libro  de ortografía:  Española, R.  A.   (2012). Ortografía  básica de  la lengua
   española,  editorial Espasa.   Elaborarás un  acordeón en  una hoja  blanca.  Un  acordeón de
   calidad puede  llevarte varios intentos,  por esta razón puedes  solicitar la revisión  de tu
   acordeón durante el semestre.
  
2. Debes ir a cualquier evento cultural publicado en la gaceta universitaria, concierto, obra de
   teatro o  conferencia realizada en  cualquier facultad distinta  a Ingeniería.  En  el evento
   debes participar en al menos una de las actividades.  Terminada la actividad, seleccionarás a
   otra persona asistente que no conozcas y grabarás en video un diálogo que tú iniciarás.

3. Podrán agregarse actividades o tareas a lo largo del semestre.

Las actividades optativas  podrán formar parte de  la clase, o bien podrán  ser solicitadas para
algún examen final.  También serán la única  forma para considerar un aumento de calificación al
final del semestre.
   
*** Exámenes finales

Tienes derecho  a dos exámenes  finales. Se llevarán  a cabo en el  horario de clase. 

- El primer examen  final corresponde a una prueba  completa de los temas vistos a  lo largo del
  semestre.   El examen  es a  documento abierto  (libros, apuntes,  copias, etc.),  pero no  se
  permitirá el  uso de dispositivos  electrónicos.  La calificación  del examen se  obtiene como
  resultado de sumar los aciertos y restar los errores presentes.

- El segundo  examen final corresponde a  una prueba que  tiene como base la  actividad optativa
  número uno. Este examen  es individual y el único documento permitido  es el producto obtenido
  de la realización de dicha actividad.

** Dinámica del curso (ejemplo)

Asistirás a  clase y escogerás una  forma de evaluación. Al  poner tu firma con  claridad en una
lista estarás comprometido a seguir los lineamientos  presentes en este documento y otros que te
serán dictados  por el profesor el  primer día de  clases. Si no  firmas en la lista  no tendrás
derecho a una calificación.

El trabajo con el cual serás calificado debes iniciarlo desde el primer día y hasta el final del
semestre. Si no puedes elegir un tema para trabajar, el profesor puede ayudarte.

El curso es mayoritariamente teórico, los ejercicios  que debes realizar para entender la teoría
están incluidos en la forma de evaluar: realiza tus trabajos y actividades continuamente.

Al hacer un aporte a  la clase se te tomará en cuenta como  participación solo si estás inscrito
en el grupo en el que hiciste el aporte, es decir, si estás inscrito en el grupo 19 pero asistes
a la  clase del  grupo 13 no  se tomarán  en cuenta estas  participaciones. Debes  solicitar tus
participaciones  diez minutos  antes de  finalizar la  sesión. Las  revisiones parciales  de tus
trabajos suman dos participaciones.

Finalmente puedes obtener participaciones cuando se solicite la actividad optativa 2 del curso o
cuando entregues  la actividad  optativa 1.  Lo  mismo pasará con  cualquier otra  actividad que
surja durante el semestre. El valor de estas actividades es de cinco participaciones.

Toda tarea, trabajo para revisión o actividad según sea el caso, será recibida hasta dos semanas
antes de finalizar el  curso (miércoles 7 y jueves 8 de noviembre  según el grupo).  Lo anterior
con el propósito de tener tiempo de revisar los trabajos entregados.

En todo tipo  de revisión durante el semestre,  entregarás tus avances cuando lo  requieras y te
serán devueltos  con las anotaciones pertinentes  tan pronto sean revisados.  Estas entregas y/o
cualquier aclaración en persona,  se llevarán a cabo únicamente durante  los primeros minutos de
la clase.

La entrega final  de los trabajos será a partir  del lunes 12 de noviembre y  hasta la fecha del
segundo examen final.

Es tu obligación estar al pendiente de tu calificación durante todo el semestre, esto significa
que debes ser consciente de lo que haces para aprobar la materia. El profesor no está obligado a
proporcionar dicha información durante el semestre.

La última clase del semestre, se cerrará el curso y se dará la orientación sobre tu calificación
si  así   lo  solicitas,  en  ninguna   otra  clase  a  lo   largo  del  curso  se   dará  dicha
orientación. Adicionalmente, se dará información sobre las fechas de examenes finales.

Deberás presentar examen  final si no obtuviste una calificación  aprobatoria (6,7,8,9,10) en el
curso. Toma en cuenta  que no es posible renunciar o subir tu  calificación. Solo podrás obtener
NP si  no hay  elementos para  calificarte. En caso  de existir  decimales la  calificación será
redondeada si es aprobatoria y los decimales mayor o igual a punto cinco.

** Rúbricas

*** R1

| Criterio                       |  ✓  |
| -----------------------------  | --- |
| Tema justificado correctamente |     |
| Movimiento 1 del método CARS   |     |
| Movimiento 2 del método CARS   |     |
| Movimiento 3 del método CARS   |     |
| Presentación en Latex          |     |

*** R2

La calificación esta determinada por los errores anotados en la siguiente tabla:

| Criterio                      | Errores | Puntos menos | Otras observaciones acerca la puntuación |
| ----------------------------- | ------- | ------------ | ---------------------------------------- |
| Coherencia y cohesión         |         |              |                                          |
| Longitud                      |         |              |                                          |
| Oraciones tópico              |         |              |                                          |
| Léxico (variedad y selección) |         |              |                                          |
| Referentes                    |         |              |                                          |
| Concordancias                 |         |              |                                          |
| Conjugación T.A.M.            |         |              |                                          |
| Separación sintáctica         |         |              |                                          |
| Citas y bibliografía          |         |              |                                          |
| Norma ortográfica             |         |              |                                          |

La calificación máxima es diez.  Si se cometen tres errores en algún criterio se resta un punto,
por cada error posterior se restará medio punto. Un error puede implicar la existencia de otro.

*** R3

| Criterio                         |  ✓  |
| -------------------------------- | --- |
| Tema justificado correctamente   |     |
| Presentó un guión o escaleta     |     |
| Presentó un texto de desarrollo  |     |
| La voz en el video es del alumno |     |
| El alumno está en el video       |     |

*** R4

La calificación esta determinada por los errores anotados en la siguiente tabla:

| Criterio             | Errores | Puntos menos | Otras observaciones acerca de la puntuación |
| -------------------- | ------- | ------------ | ------------------------------------------- |
| Presentación         |         |              |                                             |
| Registro             |         |              |                                             |
| Dicción y entonación |         |              |                                             |
| Contexto y material  |         |              |                                             |
| Información          |         |              |                                             |
| Relevancia           |         |              |                                             |
| Claridad             |         |              |                                             |
| Bibliografía         |         |              |                                             |
| Edición de video     |         |              |                                             |
| Cierre               |         |              |                                             |

La calificación máxima es diez.  Si se cometen tres errores en algún criterio se resta un punto,
por cada error posterior se restará medio punto. Un error puede implicar la existencia de otro.

** Otros elementos útiles para tu calificación

Latex es un lenguaje  de marcado útil para escribir textos. Puedes aprender  Latex por tu cuenta
viendo videos en internet o leyendo manuales. Si  no quieres instalar Latex en tu computadora te
recomiendo usar [[www.overleaf.com][Overleaf]] que es un buen editor en línea.

Algunos recursos recomendados son:

- [[https://en.wikibooks.org/wiki/LaTeX][Guía de Wikibooks sobre Latex]] (en inglés).
- Libro: [[assets/Edicion_de_textos_cientificos_LaTeX.pdf][Edición de textos científicos con Latex]]
