#+TITLE:        Evaluación Redacción y exposición de temas de ingeniería
#+AUTHOR:       Edgar Uriel Domínguez Espinoza
#+EMAIL:        reti AT genomorro DOT name
#+DATE:         2020
#+HTML_DOCTYPE: html5
#+HTML_HEAD:    <link rel="stylesheet" type="text/css" href="styles/orgcss/org.css"/>
#+LANGUAGE:     es

#+BEGIN_abstract
#+END_abstract

* Grupos, horarios y fechas importantes

- Grupo 15. Martes y jueves, 11:00 a 13:00. Salón [[https://cuaed-unam.zoom.us/j/98982402621?pwd=eldoQ1ZBTjlIZXl0MG9hdSsxOUMvZz09][I303]]. **Solo alumnos de nuevo ingreso**.
- Grupo 35. Lunes y miércoles, 15:00 a 17:00. Salón [[https://cuaed-unam.zoom.us/j/98134939473?pwd=Vm1XUE91YjVrbythNDNJN0tQNjU2UT09][A202]].
- Grupo 40. Lunes y miércoles, 17:00 a 19:00. Salón [[https://cuaed-unam.zoom.us/j/93468310227?pwd=ODZlQkpnUjdkd25UWGtXMm1wa3ZQdz09][A102]].

En  cualquier caso:  **Memoriza  tu número  de  grupo**.  El  grupo al  que  perteneces te  será
solicitado en los exámenes  u otras actividades y no será permitido  preguntarlo ni levantarse a
ver los horarios en la puerta del salón.

La clase inicia a la hora señalada en los  horarios colocados arriba, en caso de que el profesor
se retrase  más de quince minutos  la clase iniciará a  los treinta minutos. Si  pasados treinta
minutos el profesor aun está retrasado, la clase iniciará una hora después del horario oficial.

** Calendario

1. Inicio del semestre: 21 de septiembre 2020
2. Revisión de actividades optativas: 21 de septiembre 2020 al 9 de enero 2021
3. Verificación de usuario y contraseña para exámenes: 2 de noviembre de 2020
4. Entrega de evidencias finales: 11 de enero 2021 al 6 de febrero 2021
5. Fin de semestre: 30 de enero 2021
6. Informe sobre la cuenta de participaciones de cada alumno:
   1. Grupo 15: 28 de enero
   2. Grupo 35 y 40: 27 de enero
7. Exámenes finales
   1. Grupo 15: 2 de febrero 2021 y 9 de febrero 2021
   2. Grupo 35 y 40: 1 de febrero 2021 y 8 de febrero 2021

* Guía del curso

El curso tiene una guía de elementos mínimos  que debes conocer para aprobar la asignatura. Eres
el único  que tiene la  obligación de revisar  cuales son dichos  elementos y asegurarte  que el
profesor los explique durante la clase.

La guía está disponible en  formato [[file:assets/manual.pdf][PDF]] y [[file:manual.html][HTML]]. Es recomendable que tengas  una copia de la guía
durante la  clase. También  puedes ver  el temario  oficial de  la asignatura  en la  sección de
[[Lecturas]].

Las fuentes  de este sitio  pueden encontrarse en [[https://gitlab.com/genomorro/manual][gitlab]],  eres libre de  copiarlo, consultarlo,
modificarlo, corregirlo.

* Elementos de evaluación

Durante  el  semestre  no  se  tomará  en  cuenta  asistencia  ni  puntualidad  como  método  de
penalización.   Puedes llegar  y marcharte  a la  hora  que quieras.   Sin embargo  el curso  es
presencial, las participaciones determinan tu calificación. Una participación puede ser:

- Exposición ante el  grupo. Una buena exposición puede sumar  hasta tres participaciones. Puede
  realizarse durante los primeros minutos de clase (a partir de la llegada del profesor), podrás
  solicitar  la  palabra  para  exponer   sobre  alguna  lectura  (ver  actividades  optativas).
  Requisitos para  la participación: Deberás  entregar al profesor un  escrito con el  guión que
  seguiste para  realizar tu exposición  (una cuartilla), al reverso  de la hoja,  deberán estar
  impresas las rúbricas [[R2: Evaluación de textos][R2]] y [[R4: Evaluación de exposición][R4]].
- Exámenes y actividades de clase.
- Aportaciones  en  clase.   Cada  sesión  podrás solicitar  tu  participación.   El  número  de
  aportaciones será llevado por el profesor. Tus aportaciones solo serán contabilizadas si estás
  inscrito en el horario donde las hiciste.
- Entregar  actividades optativas  que  fortalezcan tu  aprendizaje. Es  una  lista variable  de
  tareas.

El  profesor   no  tiene  la   obligación  de  informarte   constantemeste  la  cuenta   de  tus
actividades. Haz tu trabajo de la mejor forma y al final del semestre tendrás el conteo preciso.

** Exámenes

Los  exámenes  son  la forma  principal  de  obtener  participaciones.   Cada examen  vale  diez
participaciones,  positivas o  negativas.   Los exámenes  no  tienen fecha  fija,  pero solo  se
realizarán al inicio o al final de la sesión. Los exámenes no podrán exceder de tres preguntas o
diez reactivos y su duración máxima será de  quince minutos, este tiempo incluye la solución del
examen por parte del profesor.

El alumno  tendrá tantas  participaciones positivas como  aciertos tenga en  el examen  y tantas
participaciones negativas  como errores tenga  en el examen.  Las preguntas sin  contestar serán
anuladas y no impactarán en la contabilización de participaciones.

**Debes tomar en cuenta que la ausencia de  un examen contará como una respuesta errónea en cada
pregunta del examen**.
*** Procedimiento para exámenes

1. El  alumno  entrará en  [[https://tao.genomorro.name][el  sitio  web  del  examen: tao.genomorro.name]]  para  contestar  el
  cuestionario.
2. La  forma de  entrar al  sitio será  con un  nombre de  usuario y  contraseña, los  cuales se
   obtendrán de la siguiente manera:

   - Nombre de usuario:
     
     Al momento de la  inscripción, cada alumno proporcionó un correo  electrónico, el nombre de
     usuario será  el mismo que  el de dicho  correo, por ejemplo,  si un alumno  proporcionó el
     correo /edgar.uriel84@gmail.com/ entonces el nombre de usuario será /edgar.uriel84/.

   - Contraseña:

     En esta página, más  abajo encontrarás una sección con tu número de  cuenta y la contraseña
     de acceso.

3.  Prueba con  anticipación  tu  acceso al  sitio,  si tienes  dudas  podrás  mandar un  correo
   electrónico al profesor  describiendo el problema. *Evita inconvenientes antes  del examen* y
   verifica tu acceso al sitio lo antes posible, la fecha límite esta en el [[Calendario][Calendario]].
** Contraseñas para exámenes
*** Contraseñas Grupo 15

| No. Cuenta | Contraseña  |
|------------+-------------|
|  318114929 | fDOgRYAqnfs |
|  318335854 | NxhzwwfxYgs |
|  318067760 | atfPb7EDLrM |
|  115007042 | ZkxzCOPP0IE |
|  318112554 | DHOSY/my4vg |
|  318143859 | u+p2Gj/A2E8 |
|  318203517 | lolo+3LGdyw |
|  318193816 | 2CFz9uM0oF8 |
|  318219330 | Bymk/xYE8XM |
|  318261126 | XYXXpeIk9jQ |
|  318720995 | 29qoAdrp4vI |
|  318025513 | gqD3olgfcWc |
|  318268015 | SHdpw8Dijqg |
|  318162384 | SFl8FqJ2QeE |
|  318199155 | uMvzUFgr9Po |
|  318213008 | l06ynvaEZp4 |
|  318014427 | cfPXukgxUA0 |
|  318134059 | FM33RCwAcsc |
|  318201245 | Issa1ELHqJQ |
|  318241254 | zzviRzQPeME |
|  318025661 | fxZs/4gqukA |
|  318285618 | 4MPkiINX98Y |
|  318270438 | NOcY7b4l3lc |
|  318113070 | AgV7/p5yDg8 |
|  318132598 | 7T0Lzmu5CKk |
|  318334424 | 3rrzFwNHIEQ |
|  318327965 | ia2xGnwbPRw |
|  318523370 | yQZrexq7mU8 |
|  318203926 | GrQqIpgNPGE |
|  318093778 | 4KInrYgyB0s |
|  318057396 | HiDV3xzVCMc |
|  318296436 | TMvbK/kvDRg |
|  318073466 | Qt6cXu5WmNc |
|  318018133 | Z606O6YTSAs |
|  318351285 | mTUzMgNmfOA |
|  318111375 | 1ueHOD0PGcU |
|  318137672 | ygl4FqR9S3Y |
|  318257204 | 5DzhzfKPTto |
|  421033755 | jEBLR2vHRl4 |
|  318273123 | 2rR3IrMiny8 |
|  421026399 | vWa2E6aj8D4 |
|  318305116 | SYr3jxgiTMk |
|  318272030 | 22lCIZ/lirY |
|  318207285 | ZuB9TJLpoXc |
|  421106448 | dUlw5IgL7E4 |
|  318311836 | CiAfaJgzsUs |
|  318099512 | KCMi4e63biI |
|  318278465 | vPiqAp/NRqw |
|  318358181 | NffrVsoLNwE |
|  318143581 | 6VvlwltlRyo |
|  318257424 | jWlV9BWPiRc |
|  318748083 | nJZYAn2ar5c |
|  318325363 | 272KpBV6yEU |
|  318033866 | eDvi7R35UpE |
|  318084057 | Zop28kUNyP8 |
|  318356125 | dLOHM/anVBY |
|  318157551 | l4V6DL4VMTY |
|  318144533 | Z7SE7klEC54 |
|  318159335 | r6orO2h0N4w |
|  318059699 | hWb5jhJNg5k |
|  318001186 | RCGvzLfWA+w |

*** Contraseñas Grupo 35

| No. Cuenta | Contraseña  |
|------------+-------------|
|  313012930 | PZs5HxaxO8E |
|  317224816 | GOp4xFc3A04 |
|  314231802 | ijuJrjWGG+o |
|  315173172 | 2mntEEpKLsw |
|  312079642 | s+3aAAQtbHk |
|  317011588 | tKnw8EezXvk |
|  317193796 | grE8n1ibSUU |
|  316010739 | JtF96mn8zLY |
|  315083556 | Aowm5Xmz450 |
|  317356490 | 0NKMtMoBN2Q |
|  311320271 | lpo/SAB6UbY |
|  314180937 | G6cYw2EKAZs |
|  315178263 | Uyl7qMsMt9A |
|  316061195 | FGSQclFGraE |
|  315037724 | BRezrNiyz24 |
|  316013565 | TgqfWW7kEmA |
|  311247767 | 7GJGx8JX5Dc |
|  316254654 | D7sNG/pNsGU |
|  317252866 | AUZ4+1pZEHg |
|  316013510 | 59SqaL0u8n0 |
|  317179211 | alcyKLLtWjU |
|  317175220 | EXbrzimCWDY |
|  312289546 | K6MCOCrAcXQ |
|  317722154 | wiKlfRWuFHs |
|  419048190 | DE88Y5KMkZs |
|  314244590 | AU1CfbsJKaI |
|  315202542 | JouOxabpOVs |
|  420055130 | hE5ADfqEorQ |
|  317306426 | aGNjzNkrShA |
|  315298242 | dskmf7L1bWc |
|  317242258 | PSsVRbw+uSg |
|  317309812 | j5JTxrVhejY |
|  419050269 | Ka6o3YFF9cg |
|  316023829 | UwTuFG8tc5M |
|  314269230 | BZO43BgcK7I |
|  317172511 | PhguWTgBnWA |
|  313150739 | LYKRMxSiFwg |
|  418046162 | RgJJSPN4WTc |
|  317030800 | FqEJM3fiIbI |
|  317309025 | yOzFv8RZcCM |
|  316078300 | GZXLyV7njmo |

*** Contraseñas Grupo 40

| No. Cuenta | Contraseña  |
|------------+-------------|
|  420054607 | IRVejqfB4oQ |
|  419047801 | htswimGlF0M |
|  317262450 | hsBiom75rDE |
|  317758715 | zrdwsDQB5CU |
|  316242341 | A2g8xMQgwg0 |
|  317020333 | +BOIGONtnss |
|  317178283 | o6p3AXX+sI0 |
|  316195065 | oX7KiBm1DC4 |
|  315192085 | 9w632z+io1s |
|  317358906 | cUkwmcDIxys |
|  317314638 | 2CA5v2f0XPM |
|  316136624 | xDjkNKN1tPM |
|  314265696 | BSUAgTs3aZ4 |
|  316036926 | Mf+yPdl9Ico |
|  315292350 | GzYK4CPCs7c |
|  419047090 | P7ICllruQuY |
|  312289467 | DW9Cpu6pAp8 |
|  315698666 | PYl+8udBjZA |
|  316062264 | zPeJFWtH+gQ |
|  420055989 | apAnDkgqmM4 |
|  314182546 | KCof88V+mvs |
|  316068060 | 8nAA0pCz0dk |
|  317024207 | 0ktk9YguGkQ |
|  316579302 | ARFeZGDhZWo |
|  317291225 | RK6YFwDESZ0 |
|  314223827 | MwhLanLhe/c |
|  313279168 | x3J9q5gxVdM |
|  317015012 | nzuh8qV8btA |
|  316242365 | zZCNfA9vj3Y |
|  317349773 | WlTG9c5A3BM |
|  310267722 | EvFG8O/C/qI |
|  317301517 | rc0ndz39TcY |
|  316259123 | meZiwvR/x6U |
|  312027753 | b94DmRIqN9Q |
|  316191782 | NrrrJaBeLDY |
|  419138558 | uv/Btg0CcAI |
|  314167301 | FVeR0pdzWxU |
|  317144808 | wY1MtbhGNvg |
|  312249142 | 02+0Qik0lMU |

** Actividades optativas

Las actividades optativas  podrán formar parte de  la clase, o bien podrán  ser solicitadas para
algún examen final.  También serán la única  forma para considerar un aumento de calificación al
final del semestre.  Entre paréntesis aparece el  número máximo de participaciones  que se puede
obtener por actividad.


1. Leerás el libro:  Real Academia Española y Asociación de Academias de  la Lengua Española, El
   buen uso  del español. Madrid: Espasa,  2013.  Podrás exponer  un resumen de un  apartado del
   libro en clase. (3P por exposición)

2. Leerás el libro de ortografía: Real Academia  Española y Asociación de Academias de la Lengua
   Española,  Ortografía básica  de la  lengua española.  Madrid: Espasa,  2012.  Elaborarás  un
   acordeón en una hoja blanca.  Un acordeón de calidad puede llevarte varios intentos, por esta
   razón puedes solicitar la revisión de tu acordeón durante el semestre. (3P)

3. Mira la escena  completa mostrada en los siguientes videos de GoT.  Identifica y describe que
   situaciones, eventos  y actos de habla  están presentes en  dicha escena. Usa las  teorías de
   Jakobson,  Austin, Searle  y  Grice  que se  vieron  en clase  para  describir  los actos  de
   habla. (2P cada video)

   - [[https://invidious.snopyta.org/watch?v=PI0OPXnBbBs][Video 1.]] Pistas adicionales: Revisa los contextos,  ¿Quién es juzgado?  ¿Quién está a favor
     y quién en contra?
   - [[https://invidious.snopyta.org/watch?v=1hZmWYh5aJg][Video 2.]] Pistas adicionales: ¿Cuál es el trato? ¿Porqué se llega a él?
   - [[https://invidious.snopyta.org/watch?v=FIer5Skcs4o][Video 3.]]  Pistas adicionales: ¿Porqué no se cumple el trato? ¿Cómo reacciona el acusado con
     el último testigo? ¿Qué dice el testigo para provocar la reacción del acusado?
   - [[https://invidious.snopyta.org/watch?v=pgdxUe2pQFM][Video  4.]] Pistas  adicionales: ¿Porqué  su amigo  no lo  defenderá?  ¿Porqué  Oberyn si  lo
     defenderá?

4. Podrán agregarse actividades  o tareas a lo largo del semestre, revisa  esta página una vez a
   la semana.

*** Revisión de actividades

Todo trabajo puede ser revisado dos veces por el  profesor previo a su entrega (Ver fechas en la
sección [[Calendario]]). Preferentemente, usa hojas de  reciclaje para las revisiones, tacha siempre
el lado que no debe ser leído.

En caso de entrega en línea, podrás usar  el correo electrónico de la asignatura. Cada actividad
será revisada lo más pronto posible, no debes preocuparte si no es revisada de inmediato.

Solo podrás  entregar una  actividad a  la vez,  con esto se  pretende que  tomes en  cuenta los
comentarios hechos trabajo a trabajo.

Las entregas finales  deben ser impresas en  hojas limpias. No deberán contener  texto escrito a
mano. No olvides colocar tu nombre y tu grupo.

*** Entrega final de actividades

- Será una sola entrega.

- Crear un archivo comprimido  tipo zip, gz, bz2 o 7z que tenga  el siguiente formato de nombre:
  NombreApellidos-Grupo, por ejemplo:  /EdgarUrielDominguezEspinoza-Gpo10.tar.gz/.  Este archivo
  contendrá el material que  el alumno realizó, incluidos los revisados  por el profesor durante
  el semestre. El archivo  contendrá tres carpetas, una por cada  forma de participar: Exámenes,
  actividades optativas, exposiciones.

- Los formatos permitidos  para entrega de tareas son preferentemente  formatos libres como PDF,
  txt, mp3, ogg, odt, ods. También se recibirán archivos doc, docx, avi, etc.

- Los archivos y carpetas deben estar nombrados en [[https://es.wikipedia.org/wiki/Camel_case][formato Camel case]], sin acentos ni espacios.

- El archivo debe ser entregado en la carpeta que corresponda:

  - [[https://nc.genomorro.name/index.php/s/kJQ9i3gPYyFqcFG][Salón I303]]

  - [[https://nc.genomorro.name/index.php/s/nKmZSpfA3CqxDFQ][Salón A202]]

  - [[https://nc.genomorro.name/index.php/s/cHiATqsJFbgqxdT][Salón A102]]

Las fechas de entrega están en la sección [[Calendario]].

** Participaciones negativas

Las participaciones  pueden ser negativas en  caso de un error  total. Un error total  puede ser
aunque no se limita a un comentario erróneo sobre un tema previamente visto, brindar información
pérfida al grupo, negarse sin motivo aparente a brindar  ayuda a la clase o brindar un texto con
numerosos errores (Ver rúbrica R2).

En las exposiciones,  un error o vacío  del expositor evidenciado por un  espectador podrá hacer
que el espectador gane las participaciones correspondientes.

Ninguna revisión es motivo de una participación negativa.

* Calificación ordinaria durante el semestre

Una vez finalizado el semestre, el  profesor contará las actividades optativas, también validará
las  calificaciones  de   los  exámenes,  sumará  las  aportaciones  de   clase  y  restará  las
participaciones negativas, de esta  forma se tendrá la cuantificación total de  cada alumno y se
procederá  a asignar  las calificaciones  según el  percentil en  el que  se encuentre  (función
percentil en hoja de cálculo):

|-----------+--------------|
| Percentil | Calificación |
|-----------+--------------|
| >=P20     |            6 |
| >=P40     |            7 |
| >=P60     |            8 |
| >=P80     |            9 |
| >=P100    |           10 |
|-----------+--------------|

Solo si  el número de  participaciones es mayor  o igual a cero  será considerado para  la tabla
anterior.

Podrás ver tu  calificación final una vez  concluido el conteo de  todo el grupo, por  lo que tu
calificación puede variar antes de esa fecha.

* Exámenes finales

Tienes derecho a dos exámenes finales:

- El primer examen  final corresponde a una prueba  completa de los temas vistos a  lo largo del
  semestre.   El examen  es a  documento abierto  (libros, apuntes,  copias, etc.),  pero no  se
  permitirá el  uso de dispositivos  electrónicos.  La calificación  del examen se  obtiene como
  resultado de sumar los aciertos y restar los errores presentes.

- El segundo  examen final corresponde a  una prueba que  tiene como base la  actividad optativa
  número uno  y dos. Este  examen es individual  y el único  documento permitido es  el producto
  obtenido de la realización de dichas  actividades.  **Requisito**: Deberás llevar la actividad
  optativa número dos en original y copia.

Las fechas de estos exámenes estarán disponibles en la sección [[Calendario]] de este sitio.

* Rúbricas
** R1: Admisión de textos

| Criterio                       | ✓ |
|--------------------------------+---|
| Tema justificado correctamente |   |
| Movimiento 1 del método CARS   |   |
| Movimiento 2 del método CARS   |   |
| Movimiento 3 del método CARS   |   |
| Presentación en Latex          |   |

** R2: Evaluación de textos

La calificación esta determinada por los errores anotados en la siguiente tabla:

| Criterio                      | Errores | Puntos menos | Otras observaciones acerca la puntuación |
|-------------------------------+---------+--------------+------------------------------------------|
| Coherencia y cohesión         |    4    |    -1.5      |                                          |
| Longitud                      |         |              |                                          |
| Oraciones tópico              |         |              |                                          |
| Léxico (variedad y selección) |         |              |                                          |
| Referentes                    |         |              |                                          |
| Concordancias                 |         |              |                                          |
| Conjugación T.A.M.            |         |              |                                          |
| Separación sintáctica         |         |              |                                          |
| Citas y bibliografía          |         |              |                                          |
| Norma ortográfica             |         |              |                                          |

La calificación máxima es diez.  Si se cometen tres errores en algún criterio se resta un punto,
por cada error posterior se restará medio punto. Un error puede implicar la existencia de otro.

** R3: Admisión de exposición

| Criterio                         | ✓ |
|----------------------------------+---|
| Tema justificado correctamente   |   |
| Presentó un guión o escaleta     |   |
| Presentó un texto de desarrollo  |   |
| La voz en el video es del alumno |   |
| El alumno está en el video       |   |

** R4: Evaluación de exposición

La calificación esta determinada por los errores anotados en la siguiente tabla:

| Criterio             | Errores | Puntos menos | Otras observaciones acerca de la puntuación |
|----------------------+---------+--------------+---------------------------------------------|
| Presentación         |         |              |                                             |
| Registro             |         |              |                                             |
| Dicción y entonación |         |              |                                             |
| Contexto y material  |         |              |                                             |
| Información          |         |              |                                             |
| Relevancia           |         |              |                                             |
| Claridad             |         |              |                                             |
| Bibliografía         |         |              |                                             |
| Edición de video     |         |              |                                             |
| Cierre               |         |              |                                             |

La calificación máxima es diez.  Si se cometen tres errores en algún criterio se resta un punto,
por cada error posterior se restará medio punto. Un error puede implicar la existencia de otro.
* Otros elementos útiles para tu calificación

** Latex

Latex es un lenguaje  de marcado útil para escribir textos. Puedes aprender  Latex por tu cuenta
viendo videos en internet o leyendo manuales. Si  no quieres instalar Latex en tu computadora te
recomiendo usar [[https://www.overleaf.com][Overleaf]] que es un buen editor en línea.

Algunos recursos recomendados son:

- [[https://en.wikibooks.org/wiki/LaTeX][Guía de Wikibooks sobre Latex]] (en inglés)
- Libro: [[file:assets/Edicion_de_textos_cientificos_LaTeX.pdf][Edición de textos científicos con Latex]]

** Lecturas                                                        :REVISAR:

- [[http://www.ingenieria.unam.mx/dcsyhfi/temarios/redaccion_y_exposicion_de_temas_de_ingenieria2016.pdf][Temario oficial de la asignatura]]
- [[http://www.aapaunam.mx/assets/julio_septiembre_2017_.pdf][Comunicación asertiva]] de Wázcar Verduzco Fragoso y Marlon Enediel Hernández Grijalba.
- [[https://teorialiteraria2009.files.wordpress.com/2009/06/barthes-la-muerte-del-autor.pdf][La muerte del autor]] de Roland Barthes.
- [[file:assets/Lecto-escritura.pdf][Manual de Lectoescritura]] de Margarita Alegría de la Colina.

* Seguridad

- La Comisión Local de Seguridad de la FI solicita la lectura de [[file:assets/acciones_cls_fi.pdf][las acciones de la CLS]].
- [[https://igualdaddegenero.unam.mx/wp-content/uploads/2019/09/nuevo-protocolo-amigable.pdf][Protocolo sobre la violencia (de género) en la UNAM]].
- [[file:assets/ProtocoloFederal.pdf][Protocolo para la prevención, atención y sanción del hostigamiento sexual y acoso sexual]].
- [[http://www.ingenieria.unam.mx/pdf/aviso_privacidad_integral.pdf][Aviso de Privacidad integral FI]].
