* Estructura de un texto escrito
** Texto: estructura y propiedades. Marcadores discursivos
- Estructura interna: Se realiza por medio de un  proceso mental que se da antes de escribir. En
  este  proceso  se  obtienen el  objetivo,  el  destinatario,  el  asunto, la  selección  y  la
  jerarquización.
- Estructura externa: Se refiere a la forma en la que el escritor lleva al papel sus ideas, está
  determinada por los  recursos de los que dispone  quien va a emitir el  mensaje. Los elementos
  que la constituyen son: el orden, el lenguaje, el estilo y el entorno.
*** Características
Estas características del texto a su vez forman el estilo del mismo.
- Claridad.
- Precisión. Principalmente al expresar la idea fundamental.
- Propiedad. En el sentido de usar términos y expresiones adecuados tanto en el significado como
  en el manejo de las normas de escritura.
- Concisión o brevedad.
- Sencillez.
*** Marcadores discursivos adverbiales
Los marcadores discursivos son nexos que guían la idea de un texto. Por lo tanto, son capaces de
unir ideas complejas, a  diferencia de las conjunciones que relacionan frases  del mismo tipo. A
continuación se muestra una clasificación por función de marcadores discursivos:

- Aditivos y  de precisión o  particularización: a  decir verdad, además,  análogamente, aparte,
  asimismo, de hecho,  encima, en el fondo, en  realidad, es más, por añadidura,  por otro lado,
  por si fuera poco, sobre todo.
- Adversativos y contraargumentativos: ahora bien, (antes)  al contrario, antes bien, después de
  todo,  empero, en  cambio,  eso  sí, no  obstante,  por el  contrario,  sin  embargo, todo  lo
  contrario.
- Concesivos: así y todo, aun así, con  todo, de cualquier manera, de todas {formas~maneras}, de
  todos modos, en cualquier caso.
- Consecutivos e  ilativos: así  pues, consiguientemente, de  {este~ese} modo,  en consecuencia,
  entonces, por consiguiente, por ende, por lo tanto, por tanto, pues.
- Explicativos: a saber, es decir, esto es, o sea.
- Reformuladores:  dicho   en  otras  palabras,  dicho  en  otros   términos,  dicho  de  otra
  {forma~manera}, de otro modo, más claramente, más llanamente, hablando en plata.
- Rectificativos: más bien, mejor dicho, por mejor decir.
- Ejemplificativos: así, así por ejemplo, así tenemos, por ejemplo, verbigracia.
- Recapitulativos: a fin de cuentas, al fin y  al cabo, en conclusión, en definitiva, en fin, en
  resumen, en resumidas cuentas, en síntesis, en suma, en una palabra, resumiendo, total.
- De   ordenación:   a   continuación,   antes   {de~que}  nada,   de   {una~otra}   parte,   en
  {primer~segundo...} lugar~término, finalmente, para empezar, para terminar, primeramente.
- De apoyo argumentativo: así las cosas, dicho esto, en vista de ello, pues bien.
- De digresión: a propósito, a todo esto, dicho sea de paso, entre paréntesis, por cierto.

Los marcadores discursivos  son capaces de relacionar párrafos, característica  que no tiene una
conjunción.
** Párrafo: características y clasificación
Un párrafo es  un conjunto de oraciones  que tratan de un  mismo tema. La forma  más sencilla de
escribir un párrafo es por medio de una lista de oraciones que predican distintas cosas sobre un
mismo referente, después esas oraciones podrán  ordenarse y relacionarse por medio de marcadores
discursivos o conjunciones.
*** Características de un párrafo
- Coherencia: Todas las oraciones tienen el mismo referente.
- Cohesión: Las  ideas expresadas  están relacionadas correctamente  unas con
  otras y por lo tanto el texto es comprensible.
- Adecuación: Las  expresiones son las  correctas para conseguir  el objetivo
  del  texto  (persuadir, demostrar,  explicar,  conmover).  Debe tomarse  en
  cuenta un público lector en particular.
- Dirección: Ver los ordenes del párrafo.
- Concreción: Se refiere a la relevancia de la información.
- Claridad.
- Sencillez: El párrafo usa oraciones en su forma menos marcada.
- Interés.
- Originalidad: El párrafo debe reflejar la personalidad del autor.

Cada  párrafo  puede reescribirse  por  medio  de  una  sola oración  que  es
explicada, detallada,  ejemplificada, argumentada  y desarrollada a  lo largo
del párrafo.  A esta  oración se  le llama /oración  tópico/ y  puede estar
explicita o implícita en el párrafo.

La oración  tópico explícita esta  escrita dentro  del párrafo y  por lo tanto  puede subrayarse
directamente. Por  otra parte,  la oración tópico  implícita debe ser  construida por  el lector,
usando el  referente del párrafo  (la coherencia)  y creando un  solo predicado que  englobe las
ideas principales.

*** Tipos de párrafo
Cada  párrafo  tiene  una  función  que  es fácilmente  identificable  por medio  de  la  oración
tópico. Para saber que  tipo de párrafo estamos leyendo hay que  preguntarnos ¿Qué está haciendo
la oración tópico? Los tipos de párrafo son los siguientes:

- Descriptivo: Explica, aclara, detalla,  ilustra, ejemplifica o argumenta la
  oración tópico.
- Comparativo: Confronta dos objetos. Su  oración tópico puede tomar la forma
  /A es más X que B/.
- Agrupador o  enumerativo: Caracteriza un objeto.  Lista las características
  del mismo por medio de viñetas o con otros recursos ortográficos.
- Problema/solución:  Ambos  elementos  están  presentes en  el  párrafo.  La
  oración tópico es  causal por lo que puede expresarse  como /Si A entonces
  B/.
*** Oraciones dentro de los párrafos
- Orden lógico: De uso frecuente en  la narración, en el recuento de eventos,
  en la explicación de procesos y direcciones.
- Orden espacial:  Para describir a lo  que se puede localizar  en un espacio
  determinado o un  lugar. Es útil en la descripción:  de arriba hacia abajo,
  de la derecha a la izquierda, etc.
- Orden de interés:  Usado para materiales que no pueden  ordenarse a base de
  tiempo o espacio:  es un orden ascendente  de lo menos importante  a lo más
  importante. Supone ir trabajando hacia un punto culminante en el párrafo.
- Orden cronológico:  De uso  frecuente en  la narración,  en el  recuento de
  eventos, en la explicación de procesos y direcciones, etc.
** Tipos de textos descriptivos-argumentativos: informe técnico, artículo científico, ensayo y tesis
*** La explicación
Responde implícita o explícitamente a estas preguntas: ¿Qué es?, ¿Cómo funciona?, ¿Por qué?

Explicar puede ser:
- Definir una palabra, fenómeno o estructura.
- Describir una serie de fenómenos o un mecanismo mostrando su funcionamiento, sus causas, sus efectos.
- Respetar una cronología y una lógica.

Se debe tener en cuenta:
- Conocimientos del receptor.
- El lenguaje especializado a utilizar.
- Registro de lengua.
*** La argumentación
Justifica una  opinión para convencer a  otro sobre la  tesis que se sustenta.  Busca convencer,
persuadir, movilizar o suscitar una acción.
**** Argumentación analógica
- Compara dos hechos o situaciones.
- Se trata de establecer una comparación entre el caso  o la opinión que se defiende y otro caso
  o situación similar.
- Lo válido en A también debe ser válido y aceptado en B.
**** Argumentación causa-efecto
Se usa cuando un fenómeno entraña a otro en función del conocimiento científico o empírico.

Refiere a la siguiente tabla de verdad:
A -> B (Se lee /Si A entonces B/)
|---+---+------|
| A | B | A->B |
|---+---+------|
| V | V | V    |
| V | F | F    |
| F | V | V    |
| F | F | V    |
|---+---+------|

Se dice que:
- A es suficiente para B
- B es necesario para A

Expresiones:
- Relación suficiente: Si...
- Relación necesaria: Solo si...
- Relación necesaria y suficiente: Si y solo si...
*** "Creating A Research Space" *CARS* model[fn:6]
**** Movimiento 1: Establecer un territorio
Se refiere a plantear la situación. Este movimiento se divide en tres pasos. Todos los pasos son
optativos, debe seleccionarse al menos uno.

- Paso 1 :: Establecer la importancia del tema.
- Paso 2 :: Hacer generalizaciones sobre el tema.
- Paso 3 :: Revisar elementos de investigaciones previas.
**** Movimiento 2: Establecer un nicho
Se refiere a establecer el  problema que se atenderá en el escrito. Consiste  en un solo paso de
puede abordarse de cuatro maneras diferentes. Debe escogerse solo una de estas opciones.

- Paso 1A :: Encontrar un contraejemplo.
- Paso 1B :: Indicar un vacío (en las investigaciones previas).
- Paso 1C :: Surgir una pregunta (sobre las investigaciones previas).
- Paso 1D :: Continuar una tradición.
**** Movimiento 3: Ocupar el nicho
Se trata de  establecer la solución al  problema planteado en el movimiento  anterior.  Se deben
seguir tres  pasos. El primer  paso puede  escribirse de dos  formas, cuya elección  depende del
avance de la investigación en el momento de escribir el texto.

- Paso 1A :: Definir propósitos (¿Porqué?).
- Paso 1B :: Anunciar la presente investigación (¿Qué?, ¿Cómo?).
- Paso 2 :: Anunciar las observaciones principales.
- Paso 3 :: Indicar la estructura del texto.

Opcionalmente, en este movimiento es posible agregar un cuarto paso. La escritura de este cuarto
paso depende nuevamente del desarrollo de la investigación en el momento de escribir el texto.

- Paso 4 :: Evaluar los descubrimientos principales.
* Notas al Pie

[fn:6] Para una explicación  detallada sobre el modelo *CARS* se recomienda  leer [[http://www.cs.tut.fi/kurssit/SGN-16006/academic_writing/cars_model_handout.pdf][el handout con
ejemplos (en inglés)]].
