* La exposición oral

La expresión  oral es  una de las  habilidades lingüísticas más  utilizas en  el día a  día. Sin
embargo, cuando se lleva  a cabo en entornos controlados, como la  exposición oral, se convierte
en una actividad laboriosa y para algunos estresante.

Para lograr una expresión oral efectiva es necesario realizar ciertas actividades previas:

1. Estudiar cuidadosamente  el tema. Se debe investigar  y comprender el tema de  la mejor forma
   posible.
2. Diseñar  un  discurso. Con  la  información  del  paso  anterior, se  debe  seleccionar  que
   información amerita  ser dicha durante  la exposición. Toma en  cuenta el tiempo  que tendrás
   disponible, por lo general suele variar de diez a veinte minutos.
3. Práctica. El discurso  diseñado debe ser ensayado con anticipación. La  forma más sencilla de
   conseguir una practica eficiente es platicar sobre el tema cada vez que sea posible.

Opcionalmente, es recomendado poner especial atención en la apertura y cierre del discurso.

** Pautas para una expresión adecuada

Es   posible  diagnosticar   las   habilidades   que  un   hablante   tiene   sobre  la   lengua
[[cite:echeverria1997estructura]],  algunos   de  los   aspectos  importantes  son   los  siguientes
cite:gomez2000lengua:

1. Tiempo o velocidad. Se  refiere al tiempo en que se realiza el acto  de habla. El tiempo debe
   ser el adecuado para que la idea sea clara para el auditorio.
2. Fluidez. Se manifiesta en la soltura con la que se da el acto de habla.
3. Ritmo  y entonación.   Es la cualidad  de imprimir  relieve a las  variaciones de  tono.  Es
   necesario poner especial atención en las exclamaciones e interrogaciones.
4. Tensión en la articulación. El hablante  debe variar el énfasis, esto es posible considerando
   los tres puntos anteriores.
5. Nitidez en el timbre vocálico. Evita la distorsión de los sonidos.

