* La redacción
** Características de una buena redacción
- Contar con información suficiente, precisa y veraz para comunicarla en forma escrita.
- Conocer y saber aplicar las reglas básicas de ortografía y morfosintaxis.
- Antes de escribir, realizar un proceso de reflexión  sobre lo que se va a escribir: qué, cómo,
  por qué, a quién...
- Utilizar  siempre un  buen diccionario  para  resolver las  dudas ortográficas  que surjan  al
  escribir.
- Leer  constantemente y  cuando se  desconozca  algún término  de  la lectura,  anotarlo en  un
  cuaderno y recurrir al diccionario.
- Una  vez realizado  el  escrito, revisarlo,  corregirlo  y leerlo  en voz  alta.  Esta es  una
  actividad imprescindible.
- Usa un corrector automático que contenga un buen tesauro.
** Operaciones básicas para la configuración de textos: descripción, narración, exposición y argumentación
*** Derechos de autor

En México, la [[http://www.diputados.gob.mx/LeyesBiblio/pdf/122_240120.pdf][Ley Federal de Derechos de Autor]] establece cuales son los derechos que los autores
tienen al crear su obra cultural. Algunos de los puntos principales de la ley son:

- Artículo 3, 4, 13 y 14. Menciona los tipos de creaciones que son objeto de los derechos de autor.
- Artículo 5. Adquisición de derechos.
- Artículo 11. Definición del derecho de autor.
- Artículo 16 y 17. Formas de dar a conocer una obra.
- Artículo 21. Derechos morales.
- Artículo 29. Duración de los derechos patrimoniales.
- Artículo 148, 149 y 151. Limitaciones para el <<uso justo>> de la obra.
- Artículo 152 y 153. El Dominio Público.
- Artículo  229 y  230. Infracciones a los derechos de autor.

*** Citas para un trabajo de investigación
Es  muy  recomendable  hacer  las  fichas  o referencias  bibliográficas  de  todos  los  libros
consultados. De  igual forma, es necesario  colocar referencias a  lo largo del trabajo  en cada
cita textual o párrafo inspirado en algún texto consultado.

La seriedad de un trabajo depende en gran medida de la investigación previa a la escritura de un
texto final.

Las  referencias sirven,  entre otras  cosas, para  que el  lector pueda  rastrear una  forma de
pensamiento plasmada  en el  trabajo, ningún pensamiento  surge de la  nada. Además,  permite al
lector ampliar la información contenida en un texto particular, lo cual eleva la credibilidad de
dicho texto.

Debemos tener presente  que la elaboración de  bibliografías es convencional, razón  por la cual
existen  muy variados  estándares  de cita,  siempre  será necesario  elegir  alguno y  seguirlo
puntualmente. En general, la información necesaria para la creación de una bibliografía completa
es la siguiente [[cite:gomez2000lengua]]:

- Autor: Nombre completo y sin abreviaturas.
- Título de la obra: En caso de existir, también el subtítulo.
- Fecha  de publicación: Siempre es preferente el año de la primera edición.

Adicionalmente, también es importante tener en cuenta:

- Nombre, número y/o volumen de la colección.
- Edición de la obra.
- Editorial.
- Lugar de la publicación de la obra.
- Páginas citadas.

Finalmente,  cuando existan  referencias  electrónicas, se  debe agregar  el  tipo de  documento
(audio, video, etc.) y la forma de publicación del mismo.
**** Normas
La forma de en que se ordenan y colocan  las citas y referencias depende de una norma. Aunque en
algunos escenarios académicos las citas parentéticas son  muy usadas no siempre son la regla. En
el siguiente enlace se encuentra un texto que muestra el uso de la norma IEEE para el área de la
ingeniería eléctrica, electrónica y computo: [[https://www.overleaf.com/read/xchzzmbjdpzd][Texto de ejemplo en Latex.]] Además es posible usarlo
como ejemplo para escribir en Latex, se recomienda leer las notas tanto en el código fuente como
en la salida a PDF.

Cada ventana de publicación busca su propia norma para citar, algunas normas populares son:

- ISO 960
- American Psychological Association (APA).
- Modern Language Association (MLA).
- IEEE
- The Chicago Manual of Style

Es posible ver que algunas normas son muy diferentes, como la norma APA (que usa las referencias
parentéticas) y  la norma  IEEE (que  usa referencias  numéricas), aunque  cumplen con  la misma
función.

En sitios como [[http://www.citationmachine.net][Citation Machine]]  es posible llenar un formulario con los dato  de la obra que se
quiere  citar  y  seleccionar  una  norma  para   obtener  la  forma  correcta  del  uso  de  la
norma. Procesadores de texto como Word y LibreOffice  ofrecen una base de datos para esta tarea,
Latex ofrece BibTeX, además hay herramientas especializadas  como Zotero o JabRef ayudan a dicha
tarea. Por lo tanto,  no es necesario aprender una norma, lo recomendable  es que la computadora
haga esas tareas de forma automática.
** Errores y deficiencias comunes en la redacción
*** El uso del gerundio
El gerundio es una forma verbal impersonal con terminación -ando -endo.
**** Uso correcto
- Con el verbo /estar/, cuando una oreación relata una acción progresiva.
- Con otros verbos cuando hay una simultaneidad en una oración finita.
- Frases que se refieren al mismo sujeto directamente.
- Si está en posición de objeto, cuando el verbo principal sea de percepción.
**** Uso incorrecto
- Cuando es consecuencia de una acción.
- Cuando se usa como adjetivo, salvo los verbos hervir y arder.
- No une oraciones yuxtapuestas.
*** Generalidades sobre tiempo y persona en un escrito
- El tiempo  presente funciona para  reavivar una narración. Sin  embargo, en
  una narración su  uso constante transmite falsedad, no todo  puede pasar en
  un mismo tiempo.
- El tiempo pasado es el tiempo eje  de una narración. Es ideal para el texto
  académico.  Tiene el  inconveniente de  ser  plano, en  otras palabras,  es
  aburrido para contar eventos.
- El tiempo futuro da al lector la percepción que tiene el escritor sobre las
  cosas  que pueden  suceder. Sirve  para hacer  suposiciones y  predicciones
  basadas en hechos y conocimientos ya establecidos.
- La primera persona es la visión limitada del narrador.
- La segunda  persona es  útil en  textos cortos  para condicionar  al lector
  porque le da instrucciones: /harás/, /dirás/, etc.
- La tercera  persona es el eje  en una narración. Otorga  el distanciamiento
  necesario para una descripción eficiente.
** Reglas básicas de ortografía
Las  reglas  de  ortografía   para  el  curso  se  encuentran  en  su   totalidad  en  el  libro
[[cite:espanola2012ortografia]].

Se recomienda la lectura del libro y la elaboración de un acordeón de una hoja tamaño carta o A4
que  contenga al  menos el  uso de  los  signos de  puntuación y  la escritura  correcta de  los
números. Este  curso de redacción  le dará al  alumno la capacidad  de entender la  totalidad de
dicho libro para que pueda seguirlo siempre que lo necesite.
